version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    env_file:
      - ./config/db.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
